version: '3.8'

services:
  task-service:
    image: task-service:latest
    build: ./task-service
    ports:
      - '3000:3000'
    depends_on:
      - kafka
      - mongo

  structure-service:
    image: structure-service:latest
    build: ./structure-service
    ports:
      - '4000:4000'
    depends_on:
      - kafka
      - neo4j

  log-service:
    image: log-service:latest
    build: ./log-service
    ports:
      - '5000:5000'
    depends_on:
      - kafka
      - mongo

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  neo4j:
    image: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
