version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/build:/usr/share/nginx/html
    depends_on:
      - task-service
      - structure-service
      - log-service

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - '5005:5005'

  structure-service:
    build: ./structure-service
    container_name: structure-service
    ports:
      - '5006:5006'

  log-service:
    build: ./log-service
    container_name: log-service
    ports:
      - '5007:5007'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/password

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
