version: '3.8'

services:
  log-service:
    image: log-service:latest
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/logs
      - KAFKA_BROKER=localhost:9092
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
